# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 15:31
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myfile',
            fields=[
                ('id', models.CharField(default=app.models.next_id, max_length=50, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=50, verbose_name='文件名')),
                ('filenumber', models.CharField(max_length=50, verbose_name='图号')),
                ('department', models.CharField(max_length=50, verbose_name='部门')),
                ('caption', models.CharField(max_length=50, verbose_name='说明')),
                ('reason', models.CharField(max_length=50, verbose_name='变更原因')),
                ('department_down', models.CharField(max_length=50, verbose_name='部门')),
                ('created_at', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('file_path', models.FileField(upload_to='./upload/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=app.models.next_id, max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
                ('admin', models.BooleanField()),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
