# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file_path',
            field=models.FileField(upload_to='./upload/', verbose_name='路径'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.BooleanField(verbose_name='管理员'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
    ]
