# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 12:06
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160830_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='file_display',
            field=models.BooleanField(default=False, verbose_name='是否可见'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='department_down',
            field=models.CharField(max_length=50, verbose_name='下发部门'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='file_path',
            field=models.FileField(upload_to=app.models.get_file_path, verbose_name='路径'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='filename',
            field=models.CharField(max_length=50, unique=True, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='filenumber',
            field=models.CharField(max_length=50, unique=True, verbose_name='图号'),
        ),
    ]
