# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160904_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proofread_user', models.CharField(max_length=50, verbose_name='校对者')),
                ('review_user', models.CharField(max_length=50, verbose_name='审核者')),
                ('countersign_user', models.CharField(max_length=50, verbose_name='会签者')),
                ('approved_user', models.CharField(max_length=50, verbose_name='批准者')),
                ('Issued_user', models.CharField(max_length=50, verbose_name='下发者')),
                ('filenumber', models.CharField(max_length=50, verbose_name='图号')),
                ('dispose_user', models.CharField(max_length=50, verbose_name='处理者')),
            ],
        ),
    ]
