# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 12:54
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='dispose_user',
            field=models.CharField(default=None, max_length=50, verbose_name='处理者'),
        ),
        migrations.AddField(
            model_name='review',
            name='file_id',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.CharField(default=app.models.next_id, max_length=50, primary_key=True, serialize=False),
        ),
    ]
