# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160907_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='dispose_user',
            field=models.CharField(default='None', max_length=50, verbose_name='处理者'),
        ),
        migrations.AlterField(
            model_name='review',
            name='file_id',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
