# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160907_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
