# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160907_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(max_length=50, null=True, verbose_name='创建者'),
        ),
    ]
